dist:
  name: otelcol-airflow
  description: Custom OpenTelemetry Collector with Airflow receiver
  output_path: ./otelcol-airflow
  otelcol_version: 0.136.0

receivers:
  - gomod: github.com/npcomplete777/airflowreceiver v0.0.0
    path: ./

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.136.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.136.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.136.0

extensions:
  - gomod: go.opentelemetry.io/collector/extension/zpagesextension v0.136.0
